### ISSUE TITLE
Dockerfile misconfiguration.

### ISSUE THREAD

**Issue by sirateek** [Catnip-Govenment-Module/government-catnip#10]
It seems that you forget to expose your container port. If so, anyone can't connect to your container if they run it individually without docker compose.

```diff
FROM python:3.9

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./app /code/app
+ # Export the container port for outsider to connect.
+ EXPOSE 80

CMD ["uvicorn", "app.main:app","--reload", "--host", "0.0.0.0", "--port", "80"]
```

Also, I highly recommend your application use the same port as you expose to the outsider to reduce misunderstanding krub.

**Comment by Jakarin-Jojo** [comment]
I already add an Export the container port for outsiders to connect.
